server:
  port: 8888
  contextPath: /api
spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1/rfsys?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd
    sql-script-encoding: UTF-8
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    properties:
      hibernate:
        dialect: com.saizhang.rfsys.persistence.custom.UTF8MySQL57InnoDBDialect